### ISSUE TITLE
NPM fails installing aspnet-identity-pw because deasync@0.0.7 seems broken

### ISSUE THREAD

**Issue by steebchen** [Syncbak-Git/aspnet-identity-pw#1]
Is there a possibility to change the version or 

Full error message:
npm WARN package.json NodeJsApp@0.0.0 No repository field.
npm WARN package.json NodeJsApp@0.0.0 No license field.
\

> deasync@0.0.7 install /home/nodejsapp/node_modules/aspnet-identity-pw/node_modules/deasync
> node ./build.js

`linux-x64` exists; testing
Problem with the binary; manual build incoming
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/nodejsapp/node_modules/aspnet-identity-pw/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
../src/deasync.cc:5:1: error: ‘uv_idle_t’ does not name a type
../src/deasync.cc:7:25: error: variable or field ‘crunch_away’ declared void
../src/deasync.cc:7:25: error: ‘uv_idle_t’ was not declared in this scope
../src/deasync.cc:7:36: error: ‘handle’ was not declared in this scope
../src/deasync.cc:7:44: error: expected primary-expression before ‘int’
../src/deasync.cc:11:32: error: ‘Arguments’ does not name a type
../src/deasync.cc:11:43: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
/root/.node-gyp/0.12.4/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> Run(const int&)’:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/deasync.cc:12:15: error: within this context
../src/deasync.cc:13:18: error: ‘idler’ was not declared in this scope
../src/deasync.cc:13:25: error: ‘crunch_away’ was not declared in this scope
../src/deasync.cc:13:36: error: ‘uv_idle_start’ was not declared in this scope
../src/deasync.cc:14:26: error: ‘uv_default_loop’ was not declared in this scope
../src/deasync.cc:14:29: error: ‘UV_RUN_ONCE’ was not declared in this scope
../src/deasync.cc:14:40: error: ‘uv_run’ was not declared in this scope
../src/deasync.cc:15:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/deasync.cc:15:32: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:305:28: note: declared here
../src/deasync.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
../src/deasync.cc:19:3: error: ‘SetMethod’ is not a member of ‘node’
../src/deasync.cc:20:32: error: ‘uv_default_loop’ was not declared in this scope
../src/deasync.cc:20:36: error: ‘idler’ was not declared in this scope
../src/deasync.cc:20:41: error: ‘uv_idle_init’ was not declared in this scope
make: *** [Release/obj.target/deasync/src/deasync.o] Error 1
make: Leaving directory`/home/nodejsapp/node_modules/aspnet-identity-pw/node_modules/deasync/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab104.1
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodejsapp/node_modules/aspnet-identity-pw/node_modules/deasync
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
Build failed
npm ERR! Linux 2.6.32-042stab104.1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "aspnet-identity-pw@1.0.0"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.0.7 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.0.7 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodejsapp/npm-debug.log

**Comment by jbrunken** [comment]
This should be fixed.

**Comment by steebchen** [comment]
Thank you. 
Could you also update the npm package (I don't exactly know how this works)?

**Comment by steebchen** [comment]
Thank you. 
Could you also update the npm package?

**Comment by jbrunken** [comment]
The update is available via npm now.
